In [1]:
import pandas as pd

In [2]:
file='phonepe-pulse_raw-data_q12018-to-q22021-v0-1-5-1720351752.xlsx'

In [3]:
#load dataset
try:
    dataset=pd.read_excel(file)
    print("Data Loaded Successfully")
except:
    print("Unsuccessful")

Data Loaded Successfully

In [4]:
print(pd.ExcelFile(file).sheet_names)

['State_Txn and Users', 'State_TxnSplit', 'State_DeviceData', 'District_Txn and Users', 'District Demographics', 'Admin']

In [5]:
#Loading the State_Txn and Users dataset and display its first 5 rows.
state_txn_and_users=pd.read_excel(file, sheet_name='State_Txn and Users')
state_txn_and_users.head()

,State,Year,Quarter,Transactions,Amount (INR),ATV (INR),Registered Users,App Opens
0,Andaman & Nicobar Islands,2018,1,6658,1.463176e+07,2197.621091,6740,0
1,Andaman & Nicobar Islands,2018,2,11340,2.833854e+07,2498.989022,9405,0
2,Andaman & Nicobar Islands,2018,3,16265,5.555747e+07,3415.768284,12149,0
3,Andaman & Nicobar Islands,2018,4,23758,9.054834e+07,3811.277720,15222,0
4,Andaman & Nicobar Islands,2019,1,30486,1.022997e+08,3355.630147,18596,0

In [14]:
#Load the State_TxnSplit dataset and display its bottom 10 rows.
state_txnsplit=pd.read_excel(file, sheet_name='State_TxnSplit')
state_txnsplit.tail(10)

,State,Year,Quarter,Transaction Type,Transactions,Amount (INR),ATV (INR)
2504,West Bengal,2021,1,Peer-to-peer payments,53869075,2.022402e+11,3754.292226
2505,West Bengal,2021,1,Merchant payments,37143701,2.891834e+10,778.553104
2506,West Bengal,2021,1,Recharge & bill payments,26673733,1.133967e+10,425.124820
2507,West Bengal,2021,1,Financial Services,166727,1.754458e+08,1052.293941
2508,West Bengal,2021,1,Others,400816,2.635025e+08,657.415236
2509,West Bengal,2021,2,Peer-to-peer payments,64661051,2.308123e+11,3569.572026
2510,West Bengal,2021,2,Merchant payments,41696787,3.478787e+10,834.305703
2511,West Bengal,2021,2,Recharge & bill payments,34799709,1.333145e+10,383.090958
2512,West Bengal,2021,2,Financial Services,190537,1.864665e+08,978.636630
2513,West Bengal,2021,2,Others,549353,3.167447e+08,576.577748

In [7]:
#Load the State_DeviceData dataset and display 10 rows from the middle of the dataset. ( 5 rows above and 5 rows below of middle row)
state_devicedata=pd.read_excel(file, sheet_name='State_DeviceData')
mid_index=len(state_devicedata)//2
state_devicedata.iloc[mid_index-5:mid_index+5]

            State  Year  Quarter     Brand  Registered Users  Percentage
2767       Ladakh  2021        2   OnePlus              1741    0.023198
2768       Ladakh  2021        2  Motorola               922    0.012285
2769       Ladakh  2021        2    Huawei               894    0.011912
2770       Ladakh  2021        2    Lenovo               490    0.006529
2771       Ladakh  2021        2    Others              2610    0.034778
2772  Lakshadweep  2018        1   Samsung               102    0.203593
2773  Lakshadweep  2018        1    Xiaomi               100    0.199601
2774  Lakshadweep  2018        1      Vivo                67    0.133733
2775  Lakshadweep  2018        1      Oppo                56    0.111776
2776  Lakshadweep  2018        1    Huawei                25    0.049900

In [10]:
#Load the District_Txn and Users dataset and display its first 10 rows and last 10 rows
district_txn_and_users=pd.read_excel(file, sheet_name='District_Txn and Users')
district_txn_and_users.head(10)

,State,Year,Quarter,District,Code,Transactions,Amount (INR),ATV (INR),Registered Users,App Opens
0,Andaman & Nicobar Islands,2018,1,Nicobars,AN01,528,1.139849e+06,2158.804548,262,0
1,Andaman & Nicobar Islands,2018,1,North And Middle Andaman,AN02,442,9.316631e+05,2107.835016,632,0
2,Andaman & Nicobar Islands,2018,1,South Andaman,AN03,5688,1.256025e+07,2208.201361,5846,0
3,Andaman & Nicobar Islands,2018,2,Nicobars,AN01,1120,3.072437e+06,2743.247239,351,0
4,Andaman & Nicobar Islands,2018,2,North And Middle Andaman,AN02,825,1.317863e+06,1597.409798,911,0
5,Andaman & Nicobar Islands,2018,2,South Andaman,AN03,9395,2.394824e+07,2549.040502,8143,0
6,Andaman & Nicobar Islands,2018,3,Nicobars,AN01,1471,6.387829e+06,4342.507921,467,0
7,Andaman & Nicobar Islands,2018,3,North And Middle Andaman,AN02,1283,4.901530e+06,3820.365954,1208,0
8,Andaman & Nicobar Islands,2018,3,South Andaman,AN03,13511,4.426811e+07,3276.449742,10474,0
9,Andaman & Nicobar Islands,2018,4,Nicobars,AN01,1485,7.180859e+06,4835.595525,536,0

In [11]:
district_txn_and_users.tail(10)

,State,Year,Quarter,District,Code,Transactions,Amount (INR),ATV (INR),Registered Users,App Opens
10238,West Bengal,2021,2,Murshidabad,WB14,8602251,1.999694e+10,2324.616616,1248602,16530655
10239,West Bengal,2021,2,Nadia,WB15,5524174,1.122758e+10,2032.445525,955428,13665885
10240,West Bengal,2021,2,North Twenty Four Parganas,WB16,17258291,3.041482e+10,1762.331031,2660664,37899453
10241,West Bengal,2021,2,Paschim Bardhaman,WB17,4893774,8.731263e+09,1784.157359,789026,10545670
10242,West Bengal,2021,2,Paschim Medinipur,WB18,5051834,1.030351e+10,2039.558976,856640,16201033
10243,West Bengal,2021,2,Purba Bardhaman,WB19,3920729,7.572502e+09,1931.401639,787970,12128849
10244,West Bengal,2021,2,Purba Medinipur,WB20,6418522,1.515507e+10,2361.146027,946277,15491958
10245,West Bengal,2021,2,Purulia,WB21,1895981,2.790996e+09,1472.059252,435131,8843358
10246,West Bengal,2021,2,South Twenty Four Parganas,WB22,6661813,1.339853e+10,2011.243709,1286588,19344293
10247,West Bengal,2021,2,Uttar Dinajpur,WB23,2253385,5.564221e+09,2469.272118,392388,8184990

In [12]:
#Load the District Demographics dataset and display every 10th row.
district_demographics=pd.read_excel(file, sheet_name='District Demographics')
district_demographics[::10]

,State,District,Headquarters,Population,Area (sq km),Density,Code,Alternate Name
0,Andhra Pradesh,Anantapur,Anantapur,4083315,19130.0,213,AP01,Anantapur
10,Andhra Pradesh,Visakhapatnam,Visakhapatnam,4288113,11161.0,384,AP10,Visakhapatnam
20,Arunachal Pradesh,Lepa Rada,Basar,0,0.0,0,AR08,Lepa Rada
30,Arunachal Pradesh,Siang,Pangin,31920,2919.0,11,AR18,Siang
40,Assam,Barpeta,Barpeta,1693622,3245.0,520,AS03,Barpeta
...,...,...,...,...,...,...,...,...
700,Chandigarh,Chandigarh,Chandigarh,1055450,114.0,9258,CH01,Chandigarh
710,Jammu & Kashmir,Jammu,Jammu,1526406,3097.0,596,JK07,Jammu
720,Jammu & Kashmir,Samba,Samba,318611,913.0,318,JK17,Samba
730,Delhi,North Delhi,Sadar Bazaar,887978,59.0,14557,DL04,North
740,Puducherry,Puducherry,Pondicherry,950289,293.0,3232,PY03,Puducherry

In [13]:
#display the summary statistics (mean, median, std, etc.) for numerical columns.
state_txn_and_users.describe()

,Year,Quarter,Transactions,Amount (INR),ATV (INR),Registered Users,App Opens
count,504.000000,504.000000,5.040000e+02,5.030000e+02,504.000000,5.040000e+02,5.040000e+02
mean,2019.285714,2.357143,4.074000e+07,7.083332e+10,1993.471543,4.777501e+06,9.774471e+07
std,1.031181,1.109971,8.228714e+07,1.440902e+11,607.464894,6.644496e+06,2.042376e+08
min,2018.000000,1.000000,7.780000e+02,1.928611e+06,0.000000,5.010000e+02,0.000000e+00
25%,2018.000000,1.000000,5.925578e+05,1.167157e+09,1598.910667,1.574202e+05,0.000000e+00
50%,2019.000000,2.000000,6.217487e+06,1.051605e+10,1861.380589,1.747914e+06,2.930574e+06
75%,2020.000000,3.000000,4.363675e+07,6.947045e+10,2259.087924,7.320945e+06,8.615022e+07
max,2021.000000,4.000000,5.736165e+08,1.027958e+12,3938.733850,3.966470e+07,1.208084e+09

In [15]:
state_txnsplit.describe()

              Year      Quarter  Transactions  Amount (INR)    ATV (INR)
count  2514.000000  2514.000000  2.514000e+03  2.514000e+03  2514.000000
mean   2019.286794     2.358393  8.167446e+06  1.443978e+10  1349.927929
std       1.030807     1.109251  2.423645e+07  5.995054e+10  1534.866221
min    2018.000000     1.000000  2.000000e+00  3.439721e+01    17.198606
25%    2018.000000     1.000000  2.788075e+04  1.762412e+07   385.735827
50%    2019.000000     2.000000  2.687980e+05  1.901189e+08   720.940406
75%    2020.000000     3.000000  3.683230e+06  2.661248e+09  1352.790116
max    2021.000000     4.000000  2.795990e+08  8.721520e+11  7767.539936

In [16]:
state_devicedata.describe()

              Year      Quarter  Registered Users   Percentage
count  5544.000000  5544.000000      5.544000e+03  5544.000000
mean   2019.285714     2.357143      4.343183e+05     0.090909
std       1.030250     1.108970      9.056069e+05     0.083095
min    2018.000000     1.000000      1.000000e+01     0.006373
25%    2018.000000     1.000000      8.055750e+03     0.021588
50%    2019.000000     2.000000      7.442250e+04     0.056914
75%    2020.000000     3.000000      3.978875e+05     0.143626
max    2021.000000     4.000000      9.764252e+06     0.478367

In [17]:
district_txn_and_users.describe()

,Year,Quarter,Transactions,Amount (INR),ATV (INR),Registered Users,App Opens
count,10248.000000,10248.000000,1.024800e+04,1.024800e+04,10244.000000,1.024800e+04,1.024800e+04
mean,2019.285714,2.357143,2.003607e+06,3.542311e+09,1909.796545,2.349591e+05,4.807117e+06
std,1.030208,1.108924,9.613466e+06,1.473154e+10,600.943349,4.605978e+05,1.562541e+07
min,2018.000000,1.000000,0.000000e+00,0.000000e+00,84.944283,2.200000e+01,0.000000e+00
25%,2018.000000,1.000000,1.031418e+05,1.756668e+08,1554.589051,3.619550e+04,0.000000e+00
50%,2019.000000,2.000000,3.763065e+05,6.784562e+08,1863.135530,1.067640e+05,6.403025e+05
75%,2020.000000,3.000000,1.272815e+06,2.377256e+09,2203.083552,2.573165e+05,4.346320e+06
max,2021.000000,4.000000,3.487128e+08,4.444224e+11,11209.980550,1.060461e+07,5.544197e+08

In [18]:
district_demographics.describe()

         Population  Area (sq km)       Density
count  7.420000e+02    742.000000    742.000000
mean   1.668555e+06   4395.373120    838.512129
std    1.458849e+06   4254.676124   2754.406896
min    0.000000e+00      0.000000      0.000000
25%    6.530815e+05   2039.750000    198.000000
50%    1.322359e+06   3402.500000    353.000000
75%    2.297440e+06   5432.750000    686.250000
max    1.008285e+07  45652.000000  36155.000000

In [25]:
# Display data types of each column in each dataset
state_txn_and_users.dtypes

State                object
Year                  int64
Quarter               int64
Transactions          int64
Amount (INR)        float64
ATV (INR)           float64
Registered Users      int64
App Opens             int64
dtype: object

In [26]:
state_txnsplit.dtypes

State                object
Year                  int64
Quarter               int64
Transaction Type     object
Transactions          int64
Amount (INR)        float64
ATV (INR)           float64
dtype: object

In [27]:
state_devicedata.dtypes

State                object
Year                  int64
Quarter               int64
Brand                object
Registered Users      int64
Percentage          float64
dtype: object

In [28]:
district_txn_and_users.dtypes

State                object
Year                  int64
Quarter               int64
District             object
Code                 object
Transactions          int64
Amount (INR)        float64
ATV (INR)           float64
Registered Users      int64
App Opens             int64
dtype: object

In [29]:
district_demographics.dtypes

State              object
District           object
Headquarters       object
Population          int64
Area (sq km)      float64
Density             int64
Code               object
Alternate Name     object
dtype: object

In [32]:
# Identify missing values in each dataset
state_txn_and_users.isna().sum()

State               0
Year                0
Quarter             0
Transactions        0
Amount (INR)        1
ATV (INR)           0
Registered Users    0
App Opens           0
dtype: int64

In [33]:
state_txnsplit.isna().sum()

State               0
Year                0
Quarter             0
Transaction Type    0
Transactions        0
Amount (INR)        0
ATV (INR)           0
dtype: int64

In [34]:
state_devicedata.isna().sum()

State               0
Year                0
Quarter             0
Brand               0
Registered Users    0
Percentage          0
dtype: int64

In [35]:
district_txn_and_users.isna().sum()

State                0
Year                 0
Quarter              0
District             0
Code                28
Transactions         0
Amount (INR)         0
ATV (INR)            4
Registered Users     0
App Opens            0
dtype: int64

In [36]:
district_demographics.isna().sum()

State             0
District          0
Headquarters      0
Population        0
Area (sq km)      0
Density           0
Code              0
Alternate Name    0
dtype: int64

In [39]:
# Calculate the percentage of missing values for each column with missing values
(district_txn_and_users.isna().mean()*100).round(3)

State               0.000
Year                0.000
Quarter             0.000
District            0.000
Code                0.273
Transactions        0.000
Amount (INR)        0.000
ATV (INR)           0.039
Registered Users    0.000
App Opens           0.000
dtype: float64

In [41]:
(state_txnsplit.isna().mean()*100).round(3)

State               0.0
Year                0.0
Quarter             0.0
Transaction Type    0.0
Transactions        0.0
Amount (INR)        0.0
ATV (INR)           0.0
dtype: float64

In [42]:
(state_devicedata.isna().mean()*100).round(3)

State               0.0
Year                0.0
Quarter             0.0
Brand               0.0
Registered Users    0.0
Percentage          0.0
dtype: float64

In [43]:
(district_txn_and_users.isna().mean()*100).round(3)

State               0.000
Year                0.000
Quarter             0.000
District            0.000
Code                0.273
Transactions        0.000
Amount (INR)        0.000
ATV (INR)           0.039
Registered Users    0.000
App Opens           0.000
dtype: float64

In [44]:
(district_demographics.isna().mean()*100).round(3)

State             0.0
District          0.0
Headquarters      0.0
Population        0.0
Area (sq km)      0.0
Density           0.0
Code              0.0
Alternate Name    0.0
dtype: float64

In [50]:
# Highlight the column with the highest percentage of missing values in each dataset
print((state_txn_and_users.isna().mean()*100).idxmax())
print((state_txn_and_users.isna().mean()*100).max())

Amount (INR)
0.1984126984126984

In [51]:
print((state_txnsplit.isna().mean()*100).idxmax())
(state_txnsplit.isna().mean()*100).max()

State

0.0

In [52]:
print((state_devicedata.isna().mean().idxmax()))
(state_devicedata.isna().mean()*100).max()

State

0.0

In [54]:
print((district_txn_and_users.isna().mean().idxmax()))
(district_txn_and_users.isna().mean()*100).max()

Code

0.27

In [56]:
print((district_demographics.isna().mean().idxmax()))
(district_demographics.isna().mean()*100).max()

State

0.0

In [ ]:
# Calculate the total number of states and the total number of districts